import Head from "next/head";

import { Inter } from "next/font/google";
import NewTodo from "@/components/NewTodo";
import Todos from "@/components/Todos";
import axios from "axios";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const Home = (props) => {
  const [todos, setTodos] = useState(props.todos);

  const fetchTodos = async () => {
    const res = await axios.get("http://localhost:3000/api/todos");
    const fetchedTodos = res.data;
    setTodos(fetchedTodos);
  };

  const removeTodoHandler = async (id) => {
    await axios.delete("http://localhost:3000/api/todos", { data: id });

    fetchTodos();
  };

  const addTodoHandler = async (todo) => {
    await axios.post("http://localhost:3000/api/todos", { title: todo });

    fetchTodos();
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="musg-p-10">
        <NewTodo onAddTodo={addTodoHandler} />
        <Todos items={todos} onRemoveTodo={removeTodoHandler} />
      </main>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const res = await axios.get("http://localhost:3000/api/todos");
  const todos = res.data;
  return {
    props: { todos: todos },
  };
};
